#+Title: Wabot Chrome Extension

Check out the [[https://github.com/aalsuwaidi/wabot/wiki/][Wiki]] for more information.
Join the Discord at https://discord.gg/C7Txwmd for discussion

This branch is to add Selenium and Docker to run the bot, the README will be updated to include new instructions.

*To migrate existing setup:* Replace the mounted volume path to the existing Google Chrome profile, it is usually stored in =~/.config/google-chrome/=

*NOTE*: To login to WhatsApp Web, connect to the container's VNC session and scan the QR code, PyQRCode wasn't working when trying to display the QR code in the terminal.

* How to run
+ Clone the repository
+ Create =config.js= in the cloned repository and follow the same format as =config_example.js=
  + This is where you add the whitelist for the groups that your chatbot can be in. If the group is not in the whitelist, the bot will automatically leave.
+ Run the following: (Replacing the specified path with your choice)
#+BEGIN_SRC 
docker run -v /{REPLACE}/{WITH}/{CUSTOM}/{PATH}:/app/profile/ -it wabot
#+END_SRC

The mounted volume is to store the Google Chrome profile that is used to retain the logged in session between runs. 








* Terms and conditions
You will NOT use this API for marketing purposes (spam, etc.).
* Legal
This code is in no way affiliated with, authorized, maintained, sponsored or endorsed by WhatsApp or any of its affiliates or subsidiaries. This is an independent and unofficial application. *Use at your own risk*.

* Cryptography Notice
This distribution includes cryptographic software. The country in which you currently reside may have restrictions on the import, possession, use, and/or re-export to another country, of encryption software. BEFORE using any encryption software, please check your country's laws, regulations and policies concerning the import, possession, or use, and re-export of encryption software, to see if this is permitted. See http://www.wassenaar.org/ for more information.

The U.S. Government Department of Commerce, Bureau of Industry and Security (BIS), has classified this software as Export Commodity Control Number (ECCN) 5D002.C.1, which includes information security software using or performing cryptographic functions with asymmetric algorithms. The form and manner of this distribution makes it eligible for export under the License Exception ENC Technology Software Unrestricted (TSU) exception (see the BIS Export Administration Regulations, Section 740.13) for both object code and source code.
